### ISSUE TITLE
unsupportedOperation Exception when calling  pause() on imageViewEx instance

### ISSUE THREAD

**Issue by TheSikh** [frapontillo/ImageViewEx#15] opened 2013-12-09 06:28 UTC
Application got crash and throw a unsupportedOperation Exception when try to pause a animating gif

**Comment by rock3r** [comment] 2014-03-11 15:05
Closing because no details have been provided for the issue so far (no logcat, steps to reproduce, etc).

**Closed as completed by rock3r** 2014-03-11 15:05 UTC
